import type { Metadata } from 'next'
import { Jost } from 'next/font/google'

import Header from '~/components/Header'
import './globals.css'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My e-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Header />
        <main className="mt-20 flex min-h-screen flex-col items-center overflow-hidden bg-white px-1 py-4 sm:px-4 md:px-16 lg:px-28">
          {children}
        </main>
      </body>
    </html>
  )
}
